PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix siemvoc:  <https://iisg.amsterdam/siem/vocab/>
prefix b2lvoc:  <https://iisg.amsterdam/B2L/vocab/>

SELECT (COUNT(DISTINCT ?city) as ?N) # expect 792
WHERE {
  ?b2lobs b2lvoc:city ?city . 
}
LIMIT 10