PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX admissiedim: <https://iisg.amsterdam/admissiesdh/dimension/>
PREFIX sex: <https://iisg.amsterdam/admissiesdh/code/sex/>
PREFIX siem: <https://iisg.amsterdam/siem/dimension/>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>


SELECT ?id ?pob ?pob2 ?city_b2l ?cityb2 ?pop_1750 WHERE {
    ?sub admissiedim:id ?id .
    ?sub admissiedim:pob_modern ?pob .
 
  	?city siem:city ?city_b2l .
 	?city siem:year "1750"^^xsd:gYear .
    ?city siem:inhab ?pop_1750.
  
  
  BIND(REPLACE(STR(?city_b2l),"[. - _ ( ) ,]"," ") AS ?cityb)
  BIND(STR(STRAFTER(STR(?pob), "https://iisg.amsterdam/admissiesdh/code/pob_modern/")) as ?pob2)
  BIND(STR(STRAFTER(STR(?cityb), "https://iisg amsterdam/siem/code/city/")) as ?cityb2)
 
  FILTER(fn:contains(?cityb2, ?pob2))
}
