PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix admis: <https://iisg.amsterdam/Admissieregisters_Haarlem/vocab/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix siemvoc: <https://iisg.amsterdam/siem/vocab/>

select ?origin ?city ?inhab ?origincoords ?origincoordsColor ?n {
  # get inhabitants and coords for all cities > 5k in 1750
  {
    SELECT ?city ?inhab ?siemcitycoords WHERE {
      ?sub siemvoc:city ?city .
      ?sub siemvoc:year ?year .
      ?sub siemvoc:inhab ?inhab .
      FILTER(?year = "1750-01-01"^^xsd:gYear && ?inhab > 5) .
      ?city geo:hasGeometry / geo:asWKT ?siemcitycoords .
    }
  }
  # count migrants by place of origin with coords
  {
    select ?origin ?origincoords (count(?origin) as ?n) {
      ?s admis:Origin ?origin .
      ?origin geo:hasGeometry / geo:asWKT ?origincoords .
    }
  }
  # keep only if origin_coords are within 5 km of city
  filter(bif:st_within(?siemcitycoords, ?origincoords, 5))
  
  bind (concat('viridis,', xsd:float(?n) / (?inhab)) as ?origincoordsColor)
}
order by desc(?share)
